// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe_fUi4pLSBluQXMXsxPp-4MsHN2bgNyk',
    appId: '1:510860714546:web:24b9d143655bc71fcad22b',
    messagingSenderId: '510860714546',
    projectId: 'maharah-sahem',
    authDomain: 'maharah-sahem.firebaseapp.com',
    databaseURL: 'https://maharah-sahem-default-rtdb.firebaseio.com',
    storageBucket: 'maharah-sahem.appspot.com',
    measurementId: 'G-Y3BD1FQDSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq46bQ__j_7whACkdl6cDS6UXru5ee_1w',
    appId: '1:510860714546:android:fb8d7f0cc760eff5cad22b',
    messagingSenderId: '510860714546',
    projectId: 'maharah-sahem',
    databaseURL: 'https://maharah-sahem-default-rtdb.firebaseio.com',
    storageBucket: 'maharah-sahem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQwX8amnTzSxNIk5IqiRdStAxRMM2NnFQ',
    appId: '1:510860714546:ios:4f32d9c4f98fee91cad22b',
    messagingSenderId: '510860714546',
    projectId: 'maharah-sahem',
    databaseURL: 'https://maharah-sahem-default-rtdb.firebaseio.com',
    storageBucket: 'maharah-sahem.appspot.com',
    iosBundleId: 'com.example.sahem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQwX8amnTzSxNIk5IqiRdStAxRMM2NnFQ',
    appId: '1:510860714546:ios:8a8f7d2f22873e28cad22b',
    messagingSenderId: '510860714546',
    projectId: 'maharah-sahem',
    databaseURL: 'https://maharah-sahem-default-rtdb.firebaseio.com',
    storageBucket: 'maharah-sahem.appspot.com',
    iosBundleId: 'com.example.sahem.RunnerTests',
  );
}
