// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzACmlAG9zumnbhzjLbeSQvbqi7Ojklmw',
    appId: '1:916666430458:web:cd6ffc43f513a3e0f76a43',
    messagingSenderId: '916666430458',
    projectId: 'fir-test1-b2ec3',
    authDomain: 'fir-test1-b2ec3.firebaseapp.com',
    databaseURL: 'https://fir-test1-b2ec3-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test1-b2ec3.appspot.com',
    measurementId: 'G-F6HV9YESTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLZpfuaMvh_h8cI9hEFfXKO7P3gRVIjNg',
    appId: '1:916666430458:android:0de290aaf4333520f76a43',
    messagingSenderId: '916666430458',
    projectId: 'fir-test1-b2ec3',
    databaseURL: 'https://fir-test1-b2ec3-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test1-b2ec3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf_Y-_5dAD_ejW4bWq90jIXzvltqfGSNA',
    appId: '1:916666430458:ios:7ec4654009d4afc4f76a43',
    messagingSenderId: '916666430458',
    projectId: 'fir-test1-b2ec3',
    databaseURL: 'https://fir-test1-b2ec3-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test1-b2ec3.appspot.com',
    androidClientId: '916666430458-30msh47pulc717e9ufevqeqkd6ejmjs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sahem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf_Y-_5dAD_ejW4bWq90jIXzvltqfGSNA',
    appId: '1:916666430458:ios:81fdf4e882fec359f76a43',
    messagingSenderId: '916666430458',
    projectId: 'fir-test1-b2ec3',
    databaseURL: 'https://fir-test1-b2ec3-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test1-b2ec3.appspot.com',
    androidClientId: '916666430458-30msh47pulc717e9ufevqeqkd6ejmjs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sahem.RunnerTests',
  );
}
